# 1. Write a short Python script that generates a random dataset of 10 users, each with two features: number of daily app opens and average session duration (in minutes). Print the dataset as a list of dictionaries.

In [6]:
import pandas as pd
import random

In [9]:
user_dataset = []

for user in range(1,11):

    opens = random.randint(2,20)

    duration = random.uniform(1.5,30.0)
    rounded_duration = round(duration, 1)

    user_info = {
        "user_id": f"User_{user}",
        "daily_app_opens": opens,
        "avg_session_duration_mins": rounded_duration
    }

    user_dataset.append(user_info)

In [11]:
user_dataset

[{'user_id': 'User_1',
  'daily_app_opens': 19,
  'avg_session_duration_mins': 3.6},
 {'user_id': 'User_2',
  'daily_app_opens': 18,
  'avg_session_duration_mins': 17.2},
 {'user_id': 'User_3',
  'daily_app_opens': 20,
  'avg_session_duration_mins': 10.3},
 {'user_id': 'User_4',
  'daily_app_opens': 6,
  'avg_session_duration_mins': 25.6},
 {'user_id': 'User_5',
  'daily_app_opens': 4,
  'avg_session_duration_mins': 24.0},
 {'user_id': 'User_6',
  'daily_app_opens': 3,
  'avg_session_duration_mins': 13.9},
 {'user_id': 'User_7',
  'daily_app_opens': 4,
  'avg_session_duration_mins': 29.8},
 {'user_id': 'User_8', 'daily_app_opens': 9, 'avg_session_duration_mins': 4.8},
 {'user_id': 'User_9',
  'daily_app_opens': 2,
  'avg_session_duration_mins': 12.2},
 {'user_id': 'User_10',
  'daily_app_opens': 4,
  'avg_session_duration_mins': 2.3}]

In [10]:
df = pd.DataFrame(user_dataset)
df

   user_id  daily_app_opens  avg_session_duration_mins
0   User_1               19                        3.6
1   User_2               18                       17.2
2   User_3               20                       10.3
3   User_4                6                       25.6
4   User_5                4                       24.0
5   User_6                3                       13.9
6   User_7                4                       29.8
7   User_8                9                        4.8
8   User_9                2                       12.2
9  User_10                4                        2.3

# 2. Create a table comparing supervised and unsupervised learning in at least 4 points, using real-world app examples (like Instagram feed ranking for supervised, Spotify playlist grouping for unsupervised).



| Feature | Supervised Learning | Unsupervised Learning |
| :--- | :--- | :--- |
| **The Main Idea** | Learning with a guide. You give the model the answers during training. | Learning by exploring. The model has to figure out the patterns on its own. |
| **Data Type** | **Labeled data** (Inputs have matching, known outputs). | **Unlabeled data** (Just raw information with no labels). |
| **Goal** | To **predict** a specific result (like a number or a category). | To **group** similar things together or find hidden structures. |
| **Real-World App** | **Instagram Feed Ranking:** It tracks what you've liked in the past to predict and rank what you'll want to see next. | **Spotify Playlist Grouping:** It looks at audio features to bunch similar-sounding songs together into a mood or genre. |
| **Common Tools** | Linear Regression, Decision Trees. | K-Means Clustering, PCA. |

---

## App Examples

### 1. Supervised Learning (The "Teacher-Student" Approach)
Think of supervised learning like studying for an exam with an answer key. The algorithm looks at past examples where the correct answer is already known, learns the pattern, and then applies that logic to new questions.

* **How Instagram uses it:** Every time you hit the "like" button, share a reel, or leave a comment, you are labeling that content as "stuff I enjoy." Instagram's algorithm takes all these labeled examples to build a personalized model for you. When you open the app, it uses that model to predict how likely you are to engage with new posts, putting your favorite creators right at the top of your feed.

### 2. Unsupervised Learning (The "Sorting Hat" Approach)
Unsupervised learning is like being handed a massive box of random photos and being told to sort them into piles without any instructions. Nobody tells the algorithm what the groups should be; it just looks for features that look similar and clusters them together.

* **How Spotify uses it:** Spotify has millions of songs and needs a way to organize them. Without a human manually tagging every single track as "chill acoustic" or "workout electronic," the algorithm looks at raw audio data—like the tempo, energy level, and instruments used. It automatically groups similar tracks into clusters, which is how you get uniquely curated buckets of music in your Discover Weekly playlists.

# 3. Given a list of 8 products with their price and number of reviews, use any method (even manual grouping) to segment them into 2-3 clusters based on similarity. Explain your reasoning for each cluster.<br><br><em><strong>Hint:</strong> Think about which products are similar in both price and popularity (reviews).</em>

In [14]:
products = [
    {"name": "Wireless Mouse", "price": 20, "reviews": 950},
    {"name": "Premium Noise-Canceling Headphones", "price": 250, "reviews": 310},
    {"name": "USB-C Charging Cable", "price": 12, "reviews": 2100},
    {"name": "Luxury Smartwatch", "price": 380, "reviews": 65},
    {"name": "Bluetooth Speaker", "price": 55, "reviews": 450},
    {"name": "High-End Ergonomic Desk Chair", "price": 450, "reviews": 40},
    {"name": "Basic Matte Phone Case", "price": 15, "reviews": 1800},
    {"name": "Budget Wired Earphones", "price": 18, "reviews": 1200}
]

df = pd.DataFrame(products)
df

                                 name  price  reviews
0                      Wireless Mouse     20      950
1  Premium Noise-Canceling Headphones    250      310
2                USB-C Charging Cable     12     2100
3                   Luxury Smartwatch    380       65
4                   Bluetooth Speaker     55      450
5       High-End Ergonomic Desk Chair    450       40
6              Basic Matte Phone Case     15     1800
7              Budget Wired Earphones     18     1200

In [15]:
cluster_1 = []  
cluster_2 = []  
cluster_3 = []

for i in products:

    if i['price'] < 30 and i['reviews'] > 900:
        cluster_1.append(i)

    elif i['price'] > 200 and i['reviews'] < 400:
        cluster_2.append(i)

    else:
        cluster_3.append(i)

In [23]:
print('cluster_1: Cheap and popular \n')
for i in cluster_1:
    print(i)

cluster_1: Cheap and popular

{'name': 'Wireless Mouse', 'price': 20, 'reviews': 950}
{'name': 'USB-C Charging Cable', 'price': 12, 'reviews': 2100}
{'name': 'Basic Matte Phone Case', 'price': 15, 'reviews': 1800}
{'name': 'Budget Wired Earphones', 'price': 18, 'reviews': 1200}

In [24]:
print('cluster_2: Luxury items \n')
for i in cluster_2:
    print(i)

cluster_2: Luxury items

{'name': 'Premium Noise-Canceling Headphones', 'price': 250, 'reviews': 310}
{'name': 'Luxury Smartwatch', 'price': 380, 'reviews': 65}
{'name': 'High-End Ergonomic Desk Chair', 'price': 450, 'reviews': 40}

In [25]:
print('cluster_3: mid range items\n')
for i in cluster_3:
    print(i)

cluster_3: mid range items

{'name': 'Bluetooth Speaker', 'price': 55, 'reviews': 450}

# 4. List 3 scenarios in Zomato, Flipkart, or Spotify where unsupervised learning could be used to discover hidden patterns or group users/items. For each, briefly describe what data would be needed and what insights might be found.

**Scenario 1:** Spotify — Discovering Niche "Vibes" (Micro-Genres)
Instead of just sticking songs into broad buckets like "Pop" or "Rock," Spotify can use unsupervised learning to find hyper-specific musical moods that humans might not even have a name for yet.

**Data needed:** Raw song attributes (like tempo, beats per minute, how acoustic it is, or how energetic it feels) combined with what time of day people listen to them.

**What it uncovers:** The algorithm might find a hidden cluster of slow-tempo, instrumental songs that tons of people play between 11 PM and 2 AM. Even if some are electronic and others are jazz, they share the exact same "late-night winding down" vibe. Spotify can use this hidden group to auto-generate unique playlists like "Deep Focus" or "Midnight Chill."

**Scenario 2:** Flipkart — Finding Hidden Shopping Personalities
Flipkart can group shoppers based on how they behave on the app, rather than just what categories they click on. This helps them understand different types of buyers.

**Data needed:** How often people open the app, how long they stare at a product before moving on, how often they leave things in their cart, and if they only buy things when there's a discount tag.

**What it uncovers:** The model will naturally group users into "shopping personalities." For example, it might find a massive cluster of Window Shoppers—people who add 15 items to their cart every week but never actually check out. It might also spot Bargain Hunters who only buy when a 50% off banner is live. Flipkart can use this to send a custom discount code just to the window shoppers to convince them to buy.

**Scenario 3:** Zomato — Spotting Neighborhood Food Trends
Zomato can use clustering to figure out what kind of food sub-cultures are popping up in different parts of a city without anyone manually tracking it.

**Data needed:** Delivery locations, what time orders are placed, the price range of the food, and common words written in user reviews (like "healthy," "keto," "spicy," or "late-night").

**What it uncovers:** The algorithm might discover a distinct cluster of orders centered right around a specific IT park or college campus, where users constantly order high-protein, healthy meals specifically between 1 PM and 3 PM. Spotting this hidden trend tells Zomato exactly what kind of new restaurants or cloud kitchens they should invite onto the app in that specific neighborhood to make more money.

# 5. Find a real-world dataset (CSV or Excel) online that could be used for customer segmentation (for example, mall customers, e-commerce users, or music listeners). Share the link and describe the structure: how many features, what kind of data, and whether it’s labeled or unlabeled.<br><br><em><strong>Hint:</strong> Use Kaggle, UCI Machine Learning Repository, or Google to find your dataset.</em>

**Dataset Link**:    
https://www.kaggle.com/datasets/shwetabh123/mall-customers


**Dataset Structure & Features**    
The dataset contains exactly 5 features (columns) and 200 rows, representing individual customers of a shopping mall.

This is an unlabeled dataset.

Why? There is no pre-existing "answer" or "target category" column that tells you who the high-value or low-value customers are.

How it's used: Because it has no target label, businesses run unsupervised algorithms (like K-Means Clustering) on the Annual Income and Spending Score columns to let the computer automatically discover the natural customer segments on its own.